# Generated by Django 4.2.6 on 2023-11-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aprendiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="fotos_aprendices")),
                ("documento", models.IntegerField()),
                ("nombre", models.CharField(max_length=50)),
                ("ficha", models.IntegerField()),
            ],
        ),
    ]
